# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: MIT-0

# {fact rule=cloudformation-disabled-iam-authentication@v1.0 defects=0}
Resources:
  DB:
    Type: AWS::RDS::DBInstance
    Properties:
      Engine: mysql
      # Compliant: RDS database has IAM authentication enabled.
      EnableIAMDatabaseAuthentication: true
# {/fact}
