# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: MIT-0

# {fact rule=cloudformation-s3-default-encryption-kms@v1.0 defects=1}
Resources:
  ExampleS3:
    Type: AWS::S3::Bucket
    Properties:
      # Noncompliant: Amazon S3 bucket is not encrypted with AWS KMS key.
      BucketName: my-bucket
# {/fact}
