# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: MIT-0

# {fact rule=cloudformation-db-instance-backup-enabled@v1.0 defects=0}
Resources:
  MyDB:
    Type: AWS::RDS::DBInstance
    Properties:
      # Compliant: `BackupRetentionPeriod` is greater than 0.
      BackupRetentionPeriod : 1
      MultiAZ: true
      StorageEncrypted: true
      MonitoringInterval: 5
# {/fact}