# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: MIT-0

# {fact rule=cloudformation-api-gw-domain-deny-non-tls-traffic@v1.0 defects=0}
Resources:
  myDomainName:
    Type: 'AWS::ApiGateway::DomainName'
    Properties:
      DomainName: api.mydomain.com
      # Compliant: API GW Domain Name Resources deny non-TLS traffic.
      SecurityPolicy: TLS_1_2
# {/fact}
