# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: MIT-0

# {fact rule=cloudformation-sagmakr-notebook-inst-kms@v1.0 defects=1}
Resources:
  BasicNotebookInstance:
    Type: "AWS::SageMaker::NotebookInstance"
    Properties:
      # Noncompliant: Amazon SageMaker Notebook instances are not configured with a Key Management Service (KMS) key. 
      InstanceType: "ml.t2.large"
      RoleArn: !GetAtt ExecutionRole.Arn
# {/fact}
