# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: MIT-0

# {fact rule=cloudformation-ebs-optimized-instance@v1.0 defects=0}
Resources:
  ExampleEC2:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref LatestAmiId
      InstanceType: !Ref pInstanceType
      # Compliant: `EbsOptimized` is enabled.
      EbsOptimized: true
# {/fact}