# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: MIT-0

# {fact rule=cloudformation-elasticsearch-in-vpc@v1.0 defects=0}
Resources:
  ElasticsearchDomain:
    Type: AWS::Elasticsearch::Domain
    Properties:
      DomainName: test
      # Compliant: Elasticsearch cluster is securely deployed within a VPC.
      VPCOptions:
        SecurityGroupIds:
          - sg-12345678
        SubnetIds:
          - subnet-12345678
# {/fact}
