# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: MIT-0

# {fact rule=cloudformation-unsecure-encrypt-efs@v1.0 defects=0}
Resources:
  Resource:
    Type: AWS::ECS::TaskDefinition
    DependsOn:
      - MountA
      - MountB
    Properties:
      Volumes:
        - Name: factorio
          EFSVolumeConfiguration:
            FilesystemId: !Ref Efs
            # Compliant: Encryption in transit is enabled.
            TransitEncryption: ENABLED
# {/fact}
