# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: MIT-0

# {fact rule=cloudformation-redshift-cluster-maintenance-settings-check@v1.0 defects=0}
Resources: 
  TestCluster:
    Type: AWS::Redshift::Cluster
    Properties:
      ClusterType: multi-node
      DBName: dev 
      MasterUsername: 
      MasterUserPassword:
      NodeType: 
      NumberOfNodes: 2
      AutoMaintenance: true
      # Compliant: Amazon Redshift clusters have the specified maintenance settings.
      PreferredMaintenanceWindow: Mon:09:30-Mon:10:00
# {/fact}
