# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: MIT-0

# {fact rule=cloudformation-redshift-cluster-maintenance-settings-check@v1.0 defects=1}
Resources: 
  TestCluster:
    Type: AWS::Redshift::Cluster
    Properties:
      # Noncompliant: Amazon Redshift clusters does not have the specified maintenance settings.
      ClusterType: multi-node
      DBName: dev 
      MasterUsername: 
      MasterUserPassword:
      NodeType: 
      NumberOfNodes: 2
      AllowVersionUpgrade: true
      AutomatedSnapshotRetentionPeriod: 2
# {/fact}
