# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: MIT-0

# {fact rule=cloudformation-aurora-mysql-backtracking-enabled@v1.0 defects=0}
Resources:
  ExampleRDS:
    Type: "AWS::RDS::DBCluster"
    Properties:
      StorageEncrypted: true
      EnableIAMDatabaseAuthentication: true
      # Compliant: Amazon Aurora MySQL cluster has backtracking enabled.
      BacktrackWindow: 1
      DatabaseName: MyCluster
      Engine: 'aurora-mysql'
# {/fact}