# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: MIT-0

# {fact rule=cloudformation-fsx-resources-protected@v1.0 defects=0}
Resources:
  FileSystem:
    Type: AWS::FSx::FileSystem
    Properties:
      FileSystemType: "LUSTRE"
      FileSystemTypeVersion: "2.12"
      StorageCapacity: 1200
      SubnetIds: [!ImportValue MySubnet01]
      SecurityGroupIds: [!ImportValue LustreIngressSecurityGroupId]
      # Compliant: FSx File Systems resources have LustreConfiguration set with `AutomatedBackupRetentionDays`.
      LustreConfiguration:
        DeploymentType: PERSISTENT_1
        AutomaticBackupRetentionDays: 30
# {/fact}
