# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: MIT-0

# {fact rule=cloudformation-unencryption-not-prevented@v1.0 defects=0}
Resources:
  GBAthenaWorkGroupForAmazonFederateMigrationQueries:
    Type: AWS::Athena::WorkGroup
    Condition: IsAmazonFederatedOrgPresent
    Properties:
      Description: "This workgroup is used for querying Amazon Federate migration related queries."
      Name: GBAmazonFederateMigration
      RecursiveDeleteOption: true
      State: ENABLED
      # Compliant: `WorkGroupConfiguration` prevents client disabling encryption.
      WorkGroupConfiguration:
        EnforceWorkGroupConfiguration: true
        ResultConfiguration:
          OutputLocation:
            Fn::Join:
              - ""
              - - "s3://"
                - Ref: GBAthenaQueryResultsS3Bucket
                - "/"
    DependsOn:
      - "GBAthenaQueryResultsS3Bucket"
# {/fact}
