# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: MIT-0

# {fact rule=cloudformation-cloudtrail-s3-dataevents@v1.0 defects=0}
Resources:
  ExampleTrail:
    Type: "AWS::CloudTrail::Trail"
    Properties:
      S3BucketName: !Ref BucketName
      S3KeyPrefix: "Uluru"
      IsLogging: true
      TrailName: !Ref TrailName
      EnableLogFileValidation: true
      IncludeGlobalServiceEvents: true
      IsMultiRegionTrail: true
      KMSKeyId: alias/MyAliasName
      # Compliant: CloudTrail Trail have data events being logged.
      EventSelectors:
        - DataResources:
          - Type: 'AWS::S3::Object'
            Values: ['arn:aws:s3:::']
          IncludeManagementEvents: true
          ReadWriteType: 'All'
        - DataResources:
          - Type: 'AWS::DynamoDB::Table'
            Values: ['arn:aws:dynamodb']
          IncludeManagementEvents: true
          ReadWriteType: 'All'
# {/fact}
