# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: MIT-0

# {fact rule=cloudformation-redshift-backup-enabled@v1.0 defects=0}
Resources: 
  TestCluster:
    Type: AWS::Redshift::Cluster
    Properties:
      ClusterType: multi-node
      DBName: dev 
      MasterUsername: 
      MasterUserPassword:
      NodeType: 
      NumberOfNodes: 2
      # Compliant: Amazon Redshift automated snapshot is enabled for clusters.
      AutomatedSnapshotRetentionPeriod: 2
# {/fact}
