# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: MIT-0

# {fact rule=cloudformation-sagmakr-notebook-acss@v1.0 defects=1}
Resources:
  BasicNotebookInstance:
    Type: "AWS::SageMaker::NotebookInstance"
    Properties:
      # Noncompliant: Amazon SageMaker Notebook instance does not have direct internet access disabled.
      InstanceType: "ml.t2.large"
      RoleArn: !GetAtt ExecutionRole.Arn
# {/fact}
