# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: MIT-0

# {fact rule=cloudformation-dynamodb-table-encryption@v1.0 defects=0}
Resources:
  Exampletable:
    Type: AWS::DynamoDB::Table
    Properties:
      KeySchema:
        - AttributeName: Id
          KeyType: HASH
      AttributeDefinitions:
        - AttributeName: Id
          AttributeType: S
        - AttributeName: dummy
          AttributeType: S
        - AttributeName: name
          AttributeType: S
        - AttributeName: owner
          AttributeType: S
        - AttributeName: createdAt
          AttributeType: S
      # Compliant: Amazon DynamoDB tables are configured with SSE.
      SSESpecification:
        SSEEnabled: true
# {/fact}
