# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: MIT-0

# {fact rule=cloudformation-timestream-not-encrypted@v1.0 defects=0}
Resources:
  TimestreamDatabase:
    Type: AWS::Timestream::Database
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete
    Properties:
      DatabaseName: SensorData
      # Compliant: Timestream database is encrypted with KMS CMK.
      KmsKeyId: kms-key-id
# {/fact}
