# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: MIT-0

# {fact rule=cloudformation-api-gw-resource-check@v1.0 defects=1}
Resources:
  myDomainName:
    Type: 'AWS::ApiGateway::DomainName'
    Properties:
      DomainName: api.mydomain.com
      SecurityPolicy: TLS_1_2
      # Noncompliant: `EndpointConfiguration` does not contain `REGIONAL`, `PRIVATE`, and/or `EDGE`.
      EndpointConfiguration:
        Types:
          - "BEYONDEDGE"
# {/fact}
