# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: MIT-0

# {fact rule=cloudformation-restrict-wildcard-kms@v1.0 defects=1}
Resources:
  Resource:
    Type: 'AWS::KMS::Key'
    Properties:
      EnableKeyRotation: true
      KeyPolicy:
        Version: 2012-10-17
        Id: !Sub ${AWS::StackName}-${AWS::AccountId}-key-policy
        Statement:
          - Sid: Allow source account access to KMS key in source account
            Effect: Allow
            # Noncompliant: KMS key policy contains wildcard(*) principal.
            Principal: '*'
            Action: kms:*
            Resource: '*'
# {/fact}
