# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: MIT-0

# {fact rule=cloudformation-cloudfront-default-root@v1.0 defects=1}
Resources:
  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      # Noncompliant: Amazon CloudFront distribution is not configured to return a specific object that is the default root object.
      DistributionConfig:
        DefaultRootObject: ""
# {/fact}
