# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: MIT-0

# {fact rule=cloudformation-cloudfront-default-root@v1.0 defects=0}
Resources:
  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      # Compliant: Amazon CloudFront distribution is configured to return a specific object that is the default root object.
      DistributionConfig:
        DefaultRootObject: index.html
# {/fact}
