# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: MIT-0

# {fact rule=cloudformation-ec2-instance-profile-attached@v1.0 defects=0}
Resources:
  ExampleEC2:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref LatestAmiId
      InstanceType: !Ref pInstanceType
      Monitoring: true
      # Compliant: IAM profile attached with the instance.
      IamInstanceProfile: !Ref rInstanceProfile
# {/fact}