# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: MIT-0

# {fact rule=cloudformation-s3-restr-public-false@v1.0 defects=1}
Resources:
  S3Bucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      # Noncompliant: S3 bucket has `restrict_public_bucket` disabled.
      AccessControl: Private
      LifecycleConfiguration:
        Rules:
          - Id: GlacierRule
            Prefix: glacier
            Status: Enabled
            ExpirationInDays: 365
            Transitions:
              - TransitionInDays: 1
                StorageClass: GLACIER
# {/fact}
