# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: MIT-0

# {fact rule=cloudformation-redshft-enhcd-vpc-rout-enbld@v1.0 defects=1}
Resources: 
  TestCluster:
    Type: AWS::Redshift::Cluster
    Properties:
      ClusterType: multi-node
      DBName: dev 
      MasterUsername: 
      MasterUserPassword:
      NodeType: 
      NumberOfNodes: 2
      # Noncompliant: Enhanced VPC Routing is disabled on Redshift clusters. 
      EnhancedVpcRouting: false
# {/fact}
