name: 'Code Review'

on: 
  pull_request: # Trigger on pull requests

jobs:
  code-review:
    runs-on: ubuntu-latest
    environment: ANTHROPIC_API_KEY
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - uses: arpitgandhi9/creview@v0.3
        env:
          NODE_OPTIONS: '--experimental-fetch'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          exclude_files: '*.json, *.md, *.yml' # Optional: Exclude files from the review
